
let name = "Marcos";
console.log(name);
console.log(typeof name);
let surname = "Lopez";
console.log(surname);
console.log(typeof surname);
let age = 32;
console.log(age);
console.log(typeof age);
let telephone = "+5491126789867";
console.log(telephone);
console.log(typeof telephone);
let socio = true ;
console.log(socio);
console.log(typeof socio);
let dateoftheMatch = "02/05/2024";
console.log(dateoftheMatch);
console.log(typeof dateoftheMatch);
let houroftheMatch = "21:09";
console.log(houroftheMatch);
console.log(typeof houroftheMatch);
let nsilla= 2;
console.log(nsilla);
console.log(typeof nsilla);
let ticketPrice = "$10022.94";
console.log(ticketPrice);
console.log(typeof ticketPrice);
let placeoftheMatch = "Estadio River Plate";
console.log(placeoftheMatch);
console.log(typeof placeoftheMatch);
let footballTeams = "River vs. Boca";
console.log(footballTeams);
console.log(typeof footballTeams);
